### ISSUE TITLE
Trouble running the install example

### ISSUE THREAD

**Issue by AndydeCleyre** [rightscale/right_chimp#8]
Mac OS X Mountain Lion
Ruby 2.0.0-p195
right_chimp 1.0.3
rest_connection 1.0.9

First, I run ```chimp --tag="rs_monitoring:state=active"``` with this result:
```
/usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- bundler (LoadError)
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/right_chimp-1.0.3/bin/chimp:9:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/bin/chimp:23:in `load'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/bin/chimp:23:in `<main>'
```

So I run ```gem install bundler``` and then ```chimp --tag="rs_monitoring:state=active"```, with this result:
```
chimp 1.0.3 executing...
/usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/rest_connection-1.0.9/lib/rest_connection/rightscale/rightscale_api_base.rb:133:in `connection': undefined method `[]=' for nil:NilClass (NoMethodError)
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/rest_connection-1.0.9/lib/rest_connection/rightscale/tag.rb:36:in `search'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/right_chimp-1.0.3/lib/right_chimp/Chimp.rb:403:in `get_servers_by_tag'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/right_chimp-1.0.3/lib/right_chimp/Chimp.rb:359:in `get_server_info'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/right_chimp-1.0.3/lib/right_chimp/Chimp.rb:117:in `run'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/right_chimp-1.0.3/bin/chimp:12:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/bin/chimp:23:in `load'
        from /usr/local/opt/rbenv/versions/2.0.0-p195/bin/chimp:23:in `<main>'
```

**Comment by markitoxs** [comment]
closing due to inactivity
